In [1]:
import sqlite3 as sql
import pandas as pd
from datetime import timedelta
import missingno as mssgno

In [2]:
def getKeyVariable(var_value):
    try:
        var_value.astype(float)
        return var_value + ":"
    except:
        return ""

# FunciÃ³n _getKeyVariable_ para identificar si existe un nombre clave de la variable, si no existe retorna ""

In [3]:
def getKeyVariable(var_value):
    try:
        var_value.astype(float)
        return var_value + ":"
    except:
        return ""

In [4]:
def getTimestamp(tmYear, tmMonth, tmDay, tmHour, tmMin):
    tsDate = str(tmYear) + "/" + str(tmMonth) + "/" + str(tmDay)
    tsDate = pd.to_datetime(tsDate, format="%Y/%m/%d")
    if (tmHour > 23):
        tmHour = 0
        tsDate += timedelta(days=1)
    tsDate = tsDate.replace(hour=tmHour, minute=tmMin)
    return tsDate

In [5]:
myconn = sql.connect("eplusout.sql")
mycursor = myconn.cursor()

In [6]:
comando = """SELECT ReportData.TimeIndex, ReportData.ReportDataDictionaryIndex, Time.DayType, ReportData.Value
  FROM (ReportData INNER JOIN ReportDataDictionary ON ReportData.ReportDataDictionaryIndex = ReportDataDictionary.ReportDataDictionaryIndex) 
  INNER JOIN Time ON ReportData.TimeIndex = Time.TimeIndex"""

In [7]:
nombres = ["Time Index", "Variable Index", "Type of Day", "Variable Value"]
data =pd.DataFrame( mycursor.execute(comando).fetchall(),columns=nombres)
data.dropna(inplace=True)
data  = data.pivot(index="Time Index", columns="Variable Index", values=["Variable Value"])
data

               Variable Value                                           \
Variable Index           9             11         961       962   1001
Time Index
1               792000.031471           NaN        NaN       NaN   NaN
2               792000.031471           NaN        NaN       NaN   NaN
3               792000.031471           NaN        NaN       NaN   NaN
4               792000.031471           NaN        NaN       NaN   NaN
5               792000.031471           NaN        NaN       NaN   NaN
...                       ...           ...        ...       ...   ...
61496           792000.031471           NaN        NaN       NaN   NaN
61497           792000.031471           NaN        NaN       NaN   NaN
61498           792000.031471           NaN        NaN       NaN   NaN
61499           792000.031471           NaN        NaN       NaN   NaN
61500                     NaN  5.860425e+08  21.386044  88.51381  24.0

                                                                       ...  \
Variable Index       1002       1041       1042       1081       1082  ...
Time Index                                                             ...
1                     NaN        NaN        NaN        NaN        NaN  ...
2                     NaN        NaN        NaN        NaN        NaN  ...
3                     NaN        NaN        NaN        NaN        NaN  ...
4                     NaN        NaN        NaN        NaN        NaN  ...
5                     NaN        NaN        NaN        NaN        NaN  ...
...                   ...        ...        ...        ...        ...  ...
61496                 NaN        NaN        NaN        NaN        NaN  ...
61497                 NaN        NaN        NaN        NaN        NaN  ...
61498                 NaN        NaN        NaN        NaN        NaN  ...
61499                 NaN        NaN        NaN        NaN        NaN  ...
61500           40.322994  29.040881  75.307833  48.366306  21.514888  ...

                                                                              \
Variable Index         2084         2085        2088        2089        2092
Time Index
1               1121.620282  1391.810098  794.026904  883.519131  670.053141
2               1104.491887  1373.797131  779.839331  869.183109  659.378596
3               1087.350301  1355.733114  765.799653  854.986817  648.752224
4               1070.208704  1337.634048  751.960330  840.989831  638.181414
5               1053.077219  1319.513528  738.214448  827.072647  627.674290
...                     ...          ...         ...         ...         ...
61496            220.135250   332.714979  154.925395  218.193810  112.809314
61497            204.670192   310.038437  146.227629  206.881016  108.090900
61498            189.433027   287.646305  137.617520  195.638747  103.376666
61499            174.456379   265.577181  129.101137  184.430195   98.671461
61500                   NaN          NaN         NaN         NaN         NaN


Variable Index        2093        2096        2097        2100        2101
Time Index
1               712.889098  233.447864  293.350746  147.908352  169.573868
2               702.178733  229.840186  289.535630  146.373311  168.012672
3               691.513339  226.234117  285.713662  144.829478  166.440970
4               680.901512  222.632287  281.888073  143.277993  164.860184
5               670.352391  219.036669  278.061589  141.719777  163.271555
...                    ...         ...         ...         ...         ...
61496           146.909860   43.056663   66.669139   49.921813   69.293029
61497           141.150775   39.943071   61.981488   48.593064   67.331922
61498           135.395706   36.892472   57.378115   47.260107   65.406557
61499           129.645729   33.913731   52.870978   45.925062   63.510961
61500                  NaN         NaN         NaN         NaN         NaN

[61488 rows x 76 columns]

# 3. Executar comando para extraer nombre de variables

In [8]:
comando_variables = "SELECT ReportDataDictionaryIndex, KeyValue, Name, Units FROM ReportDataDictionary"
nombres = ['Index_variable','Key_variable','Name_variable','Unit_variable']
name_variables =pd.DataFrame( mycursor.execute(comando_variables).fetchall(),columns=nombres)
name_variables.set_index('Index_variable',inplace=True)
name_variables

,Key_variable,Name_variable,Unit_variable
Index_variable,,,
7,Environment,Site Outdoor Air Drybulb Temperature,C
9,,Electricity:Facility,J
11,,Electricity:Facility,J
961,TZ-D01,Zone Air Temperature,C
962,TZ-D01,Zone Air Relative Humidity,%
...,...,...,...
2093,TZ-D21 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Total Cooling Rate,W
2096,TZ-D25 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Sensible Cooling Rate,W
2097,TZ-D25 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Total Cooling Rate,W
2100,TZ-D27 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Sensible Cooling Rate,W
2101,TZ-D27 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Total Cooling Rate,W

Crear nombre compuesto para el reporte de variables que contenga clave, nombre y unidad de medida

In [9]:
name_variables["Variable Name"] = getKeyVariable(name_variables['Key_variable']) +  \
                                  + name_variables['Name_variable'] \
                                  + " (" \
                                  + name_variables['Unit_variable'] + ")"
name_variables

,Key_variable,Name_variable,Unit_variable,Variable Name
Index_variable,,,,
7,Environment,Site Outdoor Air Drybulb Temperature,C,Site Outdoor Air Drybulb Temperature (C)
9,,Electricity:Facility,J,Electricity:Facility (J)
11,,Electricity:Facility,J,Electricity:Facility (J)
961,TZ-D01,Zone Air Temperature,C,Zone Air Temperature (C)
962,TZ-D01,Zone Air Relative Humidity,%,Zone Air Relative Humidity (%)
...,...,...,...,...
2093,TZ-D21 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Total Cooling Rate,W,Zone Ideal Loads Zone Total Cooling Rate (W)
2096,TZ-D25 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Sensible Cooling Rate,W,Zone Ideal Loads Zone Sensible Cooling Rate (W)
2097,TZ-D25 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Total Cooling Rate,W,Zone Ideal Loads Zone Total Cooling Rate (W)
2100,TZ-D27 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Sensible Cooling Rate,W,Zone Ideal Loads Zone Sensible Cooling Rate (W)
2101,TZ-D27 IDEAL LOADS AIR SYSTEM,Zone Ideal Loads Zone Total Cooling Rate,W,Zone Ideal Loads Zone Total Cooling Rate (W)

In [10]:
data

               Variable Value                                           \
Variable Index           9             11         961       962   1001
Time Index
1               792000.031471           NaN        NaN       NaN   NaN
2               792000.031471           NaN        NaN       NaN   NaN
3               792000.031471           NaN        NaN       NaN   NaN
4               792000.031471           NaN        NaN       NaN   NaN
5               792000.031471           NaN        NaN       NaN   NaN
...                       ...           ...        ...       ...   ...
61496           792000.031471           NaN        NaN       NaN   NaN
61497           792000.031471           NaN        NaN       NaN   NaN
61498           792000.031471           NaN        NaN       NaN   NaN
61499           792000.031471           NaN        NaN       NaN   NaN
61500                     NaN  5.860425e+08  21.386044  88.51381  24.0

                                                                       ...  \
Variable Index       1002       1041       1042       1081       1082  ...
Time Index                                                             ...
1                     NaN        NaN        NaN        NaN        NaN  ...
2                     NaN        NaN        NaN        NaN        NaN  ...
3                     NaN        NaN        NaN        NaN        NaN  ...
4                     NaN        NaN        NaN        NaN        NaN  ...
5                     NaN        NaN        NaN        NaN        NaN  ...
...                   ...        ...        ...        ...        ...  ...
61496                 NaN        NaN        NaN        NaN        NaN  ...
61497                 NaN        NaN        NaN        NaN        NaN  ...
61498                 NaN        NaN        NaN        NaN        NaN  ...
61499                 NaN        NaN        NaN        NaN        NaN  ...
61500           40.322994  29.040881  75.307833  48.366306  21.514888  ...

                                                                              \
Variable Index         2084         2085        2088        2089        2092
Time Index
1               1121.620282  1391.810098  794.026904  883.519131  670.053141
2               1104.491887  1373.797131  779.839331  869.183109  659.378596
3               1087.350301  1355.733114  765.799653  854.986817  648.752224
4               1070.208704  1337.634048  751.960330  840.989831  638.181414
5               1053.077219  1319.513528  738.214448  827.072647  627.674290
...                     ...          ...         ...         ...         ...
61496            220.135250   332.714979  154.925395  218.193810  112.809314
61497            204.670192   310.038437  146.227629  206.881016  108.090900
61498            189.433027   287.646305  137.617520  195.638747  103.376666
61499            174.456379   265.577181  129.101137  184.430195   98.671461
61500                   NaN          NaN         NaN         NaN         NaN


Variable Index        2093        2096        2097        2100        2101
Time Index
1               712.889098  233.447864  293.350746  147.908352  169.573868
2               702.178733  229.840186  289.535630  146.373311  168.012672
3               691.513339  226.234117  285.713662  144.829478  166.440970
4               680.901512  222.632287  281.888073  143.277993  164.860184
5               670.352391  219.036669  278.061589  141.719777  163.271555
...                    ...         ...         ...         ...         ...
61496           146.909860   43.056663   66.669139   49.921813   69.293029
61497           141.150775   39.943071   61.981488   48.593064   67.331922
61498           135.395706   36.892472   57.378115   47.260107   65.406557
61499           129.645729   33.913731   52.870978   45.925062   63.510961
61500                  NaN         NaN         NaN         NaN         NaN

[61488 rows x 76 columns]

In [11]:
data.columns = [name_variables.loc[columna[1]]["Key_variable"] + ':' + name_variables.loc[columna[1]]["Variable Name"] for columna in data.columns]

In [12]:
data

,:Electricity:Facility (J),:Electricity:Facility (J),TZ-D01:Zone Air Temperature (C),TZ-D01:Zone Air Relative Humidity (%),TZ-D02:Zone Air Temperature (C),TZ-D02:Zone Air Relative Humidity (%),TZ-D03:Zone Air Temperature (C),TZ-D03:Zone Air Relative Humidity (%),TZ-D06:Zone Air Temperature (C),TZ-D06:Zone Air Relative Humidity (%),...,TZ-D18 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Sensible Cooling Rate (W),TZ-D18 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Total Cooling Rate (W),TZ-D20 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Sensible Cooling Rate (W),TZ-D20 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Total Cooling Rate (W),TZ-D21 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Sensible Cooling Rate (W),TZ-D21 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Total Cooling Rate (W),TZ-D25 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Sensible Cooling Rate (W),TZ-D25 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Total Cooling Rate (W),TZ-D27 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Sensible Cooling Rate (W),TZ-D27 IDEAL LOADS AIR SYSTEM:Zone Ideal Loads Zone Total Cooling Rate (W)
Time Index,,,,,,,,,,,,,,,,,,,,,
1,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1121.620282,1391.810098,794.026904,883.519131,670.053141,712.889098,233.447864,293.350746,147.908352,169.573868
2,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1104.491887,1373.797131,779.839331,869.183109,659.378596,702.178733,229.840186,289.535630,146.373311,168.012672
3,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1087.350301,1355.733114,765.799653,854.986817,648.752224,691.513339,226.234117,285.713662,144.829478,166.440970
4,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1070.208704,1337.634048,751.960330,840.989831,638.181414,680.901512,222.632287,281.888073,143.277993,164.860184
5,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1053.077219,1319.513528,738.214448,827.072647,627.674290,670.352391,219.036669,278.061589,141.719777,163.271555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61496,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,220.135250,332.714979,154.925395,218.193810,112.809314,146.909860,43.056663,66.669139,49.921813,69.293029
61497,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,204.670192,310.038437,146.227629,206.881016,108.090900,141.150775,39.943071,61.981488,48.593064,67.331922
61498,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,189.433027,287.646305,137.617520,195.638747,103.376666,135.395706,36.892472,57.378115,47.260107,65.406557
61499,792000.031471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,174.456379,265.577181,129.101137,184.430195,98.671461,129.645729,33.913731,52.870978,45.925062,63.510961
61500,NaN,5.860425e+08,21.386044,88.51381,24.0,40.322994,29.040881,75.307833,48.366306,21.514888,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 4. Executar comando para encontrar datos de tiempo

In [25]:

comando_tiempo = "SELECT tm.TimeIndex, tm.Year, tm.Month, tm.Day, tm.Hour, tm.Minute FROM Time AS tm"
nombres = ['timeindex','year','month','day','hour','minute']
data_timestamp = pd.DataFrame(mycursor.execute(comando_tiempo).fetchall(),columns=nombres)
data_timestamp = data_timestamp[data_timestamp.year != 0]
# data_timestamp.set_index('timeindex',inplace=True)
data_timestamp['tiempo'] = str(data_timestamp.year)+'-'+str(data_timestamp.month)+'-'+str(data_timestamp.day)
data_timestamp

,timeindex,year,month,day,hour,minute,tiempo
169,170,2006,1,1,0,10,169 2006\n170 2006\n171 2006\n1...
170,171,2006,1,1,0,20,169 2006\n170 2006\n171 2006\n1...
171,172,2006,1,1,0,30,169 2006\n170 2006\n171 2006\n1...
172,173,2006,1,1,0,40,169 2006\n170 2006\n171 2006\n1...
173,174,2006,1,1,0,50,169 2006\n170 2006\n171 2006\n1...
...,...,...,...,...,...,...,...
61496,61497,2006,12,31,23,40,169 2006\n170 2006\n171 2006\n1...
61497,61498,2006,12,31,23,50,169 2006\n170 2006\n171 2006\n1...
61498,61499,2006,12,31,24,0,169 2006\n170 2006\n171 2006\n1...
61499,61500,2006,12,31,24,0,169 2006\n170 2006\n171 2006\n1...
61500,61501,2006,12,31,24,0,169 2006\n170 2006\n171 2006\n1...

In [47]:
tmp = list(mycursor.execute(comando_tiempo).fetchall())
tmp = list(tmp)
# tmp = tmp
tmp

[(1, 0, 9, 21, 0, 10),
 (2, 0, 9, 21, 0, 20),
 (3, 0, 9, 21, 0, 30),
 (4, 0, 9, 21, 0, 40),
 (5, 0, 9, 21, 0, 50),
 (6, 0, 9, 21, 1, 0),
 (7, 0, 9, 21, 1, 0),
 (8, 0, 9, 21, 1, 10),
 (9, 0, 9, 21, 1, 20),
 (10, 0, 9, 21, 1, 30),
 (11, 0, 9, 21, 1, 40),
 (12, 0, 9, 21, 1, 50),
 (13, 0, 9, 21, 2, 0),
 (14, 0, 9, 21, 2, 0),
 (15, 0, 9, 21, 2, 10),
 (16, 0, 9, 21, 2, 20),
 (17, 0, 9, 21, 2, 30),
 (18, 0, 9, 21, 2, 40),
 (19, 0, 9, 21, 2, 50),
 (20, 0, 9, 21, 3, 0),
 (21, 0, 9, 21, 3, 0),
 (22, 0, 9, 21, 3, 10),
 (23, 0, 9, 21, 3, 20),
 (24, 0, 9, 21, 3, 30),
 (25, 0, 9, 21, 3, 40),
 (26, 0, 9, 21, 3, 50),
 (27, 0, 9, 21, 4, 0),
 (28, 0, 9, 21, 4, 0),
 (29, 0, 9, 21, 4, 10),
 (30, 0, 9, 21, 4, 20),
 (31, 0, 9, 21, 4, 30),
 (32, 0, 9, 21, 4, 40),
 (33, 0, 9, 21, 4, 50),
 (34, 0, 9, 21, 5, 0),
 (35, 0, 9, 21, 5, 0),
 (36, 0, 9, 21, 5, 10),
 (37, 0, 9, 21, 5, 20),
 (38, 0, 9, 21, 5, 30),
 (39, 0, 9, 21, 5, 40),
 (40, 0, 9, 21, 5, 50),
 (41, 0, 9, 21, 6, 0),
 (42, 0, 9, 21, 6, 0),
 (43, 0, 9, 21, 6, 10),
 (44, 0, 9, 21, 6, 20),
 (45, 0, 9, 21, 6, 30),
 (46, 0, 9, 21, 6, 40),
 (47, 0, 9, 21, 6, 50),
 (48, 0, 9, 21, 7, 0),
 (49, 0, 9, 21, 7, 0),
 (50, 0, 9, 21, 7, 10),
 (51, 0, 9, 21, 7, 20),
 (52, 0, 9, 21, 7, 30),
 (53, 0, 9, 21, 7, 40),
 (54, 0, 9, 21, 7, 50),
 (55, 0, 9, 21, 8, 0),
 (56, 0, 9, 21, 8, 0),
 (57, 0, 9, 21, 8, 10),
 (58, 0, 9, 21, 8, 20),
 (59, 0, 9, 21, 8, 30),
 (60, 0, 9, 21, 8, 40),
 (61, 0, 9, 21, 8, 50),
 (62, 0, 9, 21, 9, 0),
 (63, 0, 9, 21, 9, 0),
 (64, 0, 9, 21, 9, 10),
 (65, 0, 9, 21, 9, 20),
 (66, 0, 9, 21, 9, 30),
 (67, 0, 9, 21, 9, 40),
 (68, 0, 9, 21, 9, 50),
 (69, 0, 9, 21, 10, 0),
 (70, 0, 9, 21, 10, 0),
 (71, 0, 9, 21, 10, 10),
 (72, 0, 9, 21, 10, 20),
 (73, 0, 9, 21, 10, 30),
 (74, 0, 9, 21, 10, 40),
 (75, 0, 9, 21, 10, 50),
 (76, 0, 9, 21, 11, 0),
 (77, 0, 9, 21, 11, 0),
 (78, 0, 9, 21, 11, 10),
 (79, 0, 9, 21, 11, 20),
 (80, 0, 9, 21, 11, 30),
 (81, 0, 9, 21, 11, 40),
 (82, 0, 9, 21, 11, 50),
 (83, 0, 9, 21, 12, 0),
 (84, 0, 9, 21, 12, 0),
 (85, 0, 9, 21, 12, 10),
 (86, 0, 9, 21, 12, 20),
 (87, 0, 9, 21, 12, 30),
 (88, 0, 9, 21, 12, 40),
 (89, 0, 9, 21, 12, 50),
 (90, 0, 9, 21, 13, 0),
 (91, 0, 9, 21, 13, 0),
 (92, 0, 9, 21, 13, 10),
 (93, 0, 9, 21, 13, 20),
 (94, 0, 9, 21, 13, 30),
 (95, 0, 9, 21, 13, 40),
 (96, 0, 9, 21, 13, 50),
 (97, 0, 9, 21, 14, 0),
 (98, 0, 9, 21, 14, 0),
 (99, 0, 9, 21, 14, 10),
 (100, 0, 9, 21, 14, 20),
 (101, 0, 9, 21, 14, 30),
 (102, 0, 9, 21, 14, 40),
 (103, 0, 9, 21, 14, 50),
 (104, 0, 9, 21, 15, 0),
 (105, 0, 9, 21, 15, 0),
 (106, 0, 9, 21, 15, 10),
 (107, 0, 9, 21, 15, 20),
 (108, 0, 9, 21, 15, 30),
 (109, 0, 9, 21, 15, 40),
 (110, 0, 9, 21, 15, 50),
 (111, 0, 9, 21, 16, 0),
 (112, 0, 9, 21, 16, 0),
 (113, 0, 9, 21, 16, 10),
 (114, 0, 9, 21, 16, 20),
 (115, 0, 9, 21, 16, 30),
 (116, 0, 9, 21, 16, 40),
 (117, 0, 9, 21, 16, 50),
 (118, 0, 9, 21, 17, 0),
 (119, 0, 9, 21, 17, 0),
 (120, 0, 9, 21, 17, 10),
 (121, 0, 9, 21, 17, 20),
 (122, 0, 9, 21, 17, 30),
 (123, 0, 9, 21, 17, 40),
 (124, 0, 9, 21, 17, 50),
 (125, 0, 9, 21, 18, 0),
 (126, 0, 9, 21, 18, 0),
 (127, 0, 9, 21, 18, 10),
 (128, 0, 9, 21, 18, 20),
 (129, 0, 9, 21, 18, 30),
 (130, 0, 9, 21, 18, 40),
 (131, 0, 9, 21, 18, 50),
 (132, 0, 9, 21, 19, 0),
 (133, 0, 9, 21, 19, 0),
 (134, 0, 9, 21, 19, 10),
 (135, 0, 9, 21, 19, 20),
 (136, 0, 9, 21, 19, 30),
 (137, 0, 9, 21, 19, 40),
 (138, 0, 9, 21, 19, 50),
 (139, 0, 9, 21, 20, 0),
 (140, 0, 9, 21, 20, 0),
 (141, 0, 9, 21, 20, 10),
 (142, 0, 9, 21, 20, 20),
 (143, 0, 9, 21, 20, 30),
 (144, 0, 9, 21, 20, 40),
 (145, 0, 9, 21, 20, 50),
 (146, 0, 9, 21, 21, 0),
 (147, 0, 9, 21, 21, 0),
 (148, 0, 9, 21, 21, 10),
 (149, 0, 9, 21, 21, 20),
 (150, 0, 9, 21, 21, 30),
 (151, 0, 9, 21, 21, 40),
 (152, 0, 9, 21, 21, 50),
 (153, 0, 9, 21, 22, 0),
 (154, 0, 9, 21, 22, 0),
 (155, 0, 9, 21, 22, 10),
 (156, 0, 9, 21, 22, 20),
 (157, 0, 9, 21, 22, 30),
 (158, 0, 9, 21, 22, 40),
 (159, 0, 9, 21, 22, 50),
 (160, 0, 9, 21, 23, 0),
 (161, 0, 9, 21, 23, 0),
 (162, 0, 9, 21, 23, 10),
 (163, 0, 9, 21, 23, 20),
 (164, 0, 9, 21, 23, 30),
 (165, 0, 9, 21, 23, 40),
 (166, 0, 9, 21, 23, 50),
 (167, 0, 9, 21, 24, 0),
 (168, 0, 9, 21, 24, 0),
 (169, 0, 9, 30, 24, 0),
 (170, 2006, 1, 1, 0, 10),
 (171, 2006, 1, 1, 0, 20),
 (172, 2006, 1, 1, 0, 30),
 (173, 2006, 1, 1, 0, 40),
 (174, 2006, 1, 1, 0, 50),
 (175, 2006, 1, 1, 1, 0),
 (176, 2006, 1, 1, 1, 0),
 (177, 2006, 1, 1, 1, 10),
 (178, 2006, 1, 1, 1, 20),
 (179, 2006, 1, 1, 1, 30),
 (180, 2006, 1, 1, 1, 40),
 (181, 2006, 1, 1, 1, 50),
 (182, 2006, 1, 1, 2, 0),
 (183, 2006, 1, 1, 2, 0),
 (184, 2006, 1, 1, 2, 10),
 (185, 2006, 1, 1, 2, 20),
 (186, 2006, 1, 1, 2, 30),
 (187, 2006, 1, 1, 2, 40),
 (188, 2006, 1, 1, 2, 50),
 (189, 2006, 1, 1, 3, 0),
 (190, 2006, 1, 1, 3, 0),
 (191, 2006, 1, 1, 3, 10),
 (192, 2006, 1, 1, 3, 20),
 (193, 2006, 1, 1, 3, 30),
 (194, 2006, 1, 1, 3, 40),
 (195, 2006, 1, 1, 3, 50),
 (196, 2006, 1, 1, 4, 0),
 (197, 2006, 1, 1, 4, 0),
 (198, 2006, 1, 1, 4, 10),
 (199, 2006, 1, 1, 4, 20),
 (200, 2006, 1, 1, 4, 30),
 (201, 2006, 1, 1, 4, 40),
 (202, 2006, 1, 1, 4, 50),
 (203, 2006, 1, 1, 5, 0),
 (204, 2006, 1, 1, 5, 0),
 (205, 2006, 1, 1, 5, 10),
 (206, 2006, 1, 1, 5, 20),
 (207, 2006, 1, 1, 5, 30),
 (208, 2006, 1, 1, 5, 40),
 (209, 2006, 1, 1, 5, 50),
 (210, 2006, 1, 1, 6, 0),
 (211, 2006, 1, 1, 6, 0),
 (212, 2006, 1, 1, 6, 10),
 (213, 2006, 1, 1, 6, 20),
 (214, 2006, 1, 1, 6, 30),
 (215, 2006, 1, 1, 6, 40),
 (216, 2006, 1, 1, 6, 50),
 (217, 2006, 1, 1, 7, 0),
 (218, 2006, 1, 1, 7, 0),
 (219, 2006, 1, 1, 7, 10),
 (220, 2006, 1, 1, 7, 20),
 (221, 2006, 1, 1, 7, 30),
 (222, 2006, 1, 1, 7, 40),
 (223, 2006, 1, 1, 7, 50),
 (224, 2006, 1, 1, 8, 0),
 (225, 2006, 1, 1, 8, 0),
 (226, 2006, 1, 1, 8, 10),
 (227, 2006, 1, 1, 8, 20),
 (228, 2006, 1, 1, 8, 30),
 (229, 2006, 1, 1, 8, 40),
 (230, 2006, 1, 1, 8, 50),
 (231, 2006, 1, 1, 9, 0),
 (232, 2006, 1, 1, 9, 0),
 (233, 2006, 1, 1, 9, 10),
 (234, 2006, 1, 1, 9, 20),
 (235, 2006, 1, 1, 9, 30),
 (236, 2006, 1, 1, 9, 40),
 (237, 2006, 1, 1, 9, 50),
 (238, 2006, 1, 1, 10, 0),
 (239, 2006, 1, 1, 10, 0),
 (240, 2006, 1, 1, 10, 10),
 (241, 2006, 1, 1, 10, 20),
 (242, 2006, 1, 1, 10, 30),
 (243, 2006, 1, 1, 10, 40),
 (244, 2006, 1, 1, 10, 50),
 (245, 2006, 1, 1, 11, 0),
 (246, 2006, 1, 1, 11, 0),
 (247, 2006, 1, 1, 11, 10),
 (248, 2006, 1, 1, 11, 20),
 (249, 2006, 1, 1, 11, 30),
 (250, 2006, 1, 1, 11, 40),
 (251, 2006, 1, 1, 11, 50),
 (252, 2006, 1, 1, 12, 0),
 (253, 2006, 1, 1, 12, 0),
 (254, 2006, 1, 1, 12, 10),
 (255, 2006, 1, 1, 12, 20),
 (256, 2006, 1, 1, 12, 30),
 (257, 2006, 1, 1, 12, 40),
 (258, 2006, 1, 1, 12, 50),
 (259, 2006, 1, 1, 13, 0),
 (260, 2006, 1, 1, 13, 0),
 (261, 2006, 1, 1, 13, 10),
 (262, 2006, 1, 1, 13, 20),
 (263, 2006, 1, 1, 13, 30),
 (264, 2006, 1, 1, 13, 40),
 (265, 2006, 1, 1, 13, 50),
 (266, 2006, 1, 1, 14, 0),
 (267, 2006, 1, 1, 14, 0),
 (268, 2006, 1, 1, 14, 10),
 (269, 2006, 1, 1, 14, 20),
 (270, 2006, 1, 1, 14, 30),
 (271, 2006, 1, 1, 14, 40),
 (272, 2006, 1, 1, 14, 50),
 (273, 2006, 1, 1, 15, 0),
 (274, 2006, 1, 1, 15, 0),
 (275, 2006, 1, 1, 15, 10),
 (276, 2006, 1, 1, 15, 20),
 (277, 2006, 1, 1, 15, 30),
 (278, 2006, 1, 1, 15, 40),
 (279, 2006, 1, 1, 15, 50),
 (280, 2006, 1, 1, 16, 0),
 (281, 2006, 1, 1, 16, 0),
 (282, 2006, 1, 1, 16, 10),
 (283, 2006, 1, 1, 16, 20),
 (284, 2006, 1, 1, 16, 30),
 (285, 2006, 1, 1, 16, 40),
 (286, 2006, 1, 1, 16, 50),
 (287, 2006, 1, 1, 17, 0),
 (288, 2006, 1, 1, 17, 0),
 (289, 2006, 1, 1, 17, 10),
 (290, 2006, 1, 1, 17, 20),
 (291, 2006, 1, 1, 17, 30),
 (292, 2006, 1, 1, 17, 40),
 (293, 2006, 1, 1, 17, 50),
 (294, 2006, 1, 1, 18, 0),
 (295, 2006, 1, 1, 18, 0),
 (296, 2006, 1, 1, 18, 10),
 (297, 2006, 1, 1, 18, 20),
 (298, 2006, 1, 1, 18, 30),
 (299, 2006, 1, 1, 18, 40),
 (300, 2006, 1, 1, 18, 50),
 (301, 2006, 1, 1, 19, 0),
 (302, 2006, 1, 1, 19, 0),
 (303, 2006, 1, 1, 19, 10),
 (304, 2006, 1, 1, 19, 20),
 (305, 2006, 1, 1, 19, 30),
 (306, 2006, 1, 1, 19, 40),
 (307, 2006, 1, 1, 19, 50),
 (308, 2006, 1, 1, 20, 0),
 (309, 2006, 1, 1, 20, 0),
 (310, 2006, 1, 1, 20, 10),
 (311, 2006, 1, 1, 20, 20),
 (312, 2006, 1, 1, 20, 30),
 (313, 2006, 1, 1, 20, 40),
 (314, 2006, 1, 1, 20, 50),
 (315, 2006, 1, 1, 21, 0),
 (316, 2006, 1, 1, 21, 0),
 (317, 2006, 1, 1, 21, 10),
 (318, 2006, 1, 1, 21, 20),
 (319, 2006, 1, 1, 21, 30),
 (320, 2006, 1, 1, 21, 40),
 (321, 2006, 1, 1, 21, 50),
 (322, 2006, 1, 1, 22, 0),
 (323, 2006, 1, 1, 22, 0),
 (324, 2006, 1, 1, 22, 10),
 (325, 2006, 1, 1, 22, 20),
 (326, 2006, 1, 1, 22, 30),
 (327, 2006, 1, 1, 22, 40),
 (328, 2006, 1, 1, 22, 50),
 (329, 2006, 1, 1, 23, 0),
 (330, 2006, 1, 1, 23, 0),
 (331, 2006, 1, 1, 23, 10),
 (332, 2006, 1, 1, 23, 20),
 (333, 2006, 1, 1, 23, 30),
 (334, 2006, 1, 1, 23, 40),
 (335, 2006, 1, 1, 23, 50),
 (336, 2006, 1, 1, 24, 0),
 (337, 2006, 1, 1, 24, 0),
 (338, 2006, 1, 2, 0, 10),
 (339, 2006, 1, 2, 0, 20),
 (340, 2006, 1, 2, 0, 30),
 (341, 2006, 1, 2, 0, 40),
 (342, 2006, 1, 2, 0, 50),
 (343, 2006, 1, 2, 1, 0),
 (344, 2006, 1, 2, 1, 0),
 (345, 2006, 1, 2, 1, 10),
 (346, 2006, 1, 2, 1, 20),
 (347, 2006, 1, 2, 1, 30),
 (348, 2006, 1, 2, 1, 40),
 (349, 2006, 1, 2, 1, 50),
 (350, 2006, 1, 2, 2, 0),
 (351, 2006, 1, 2, 2, 0),
 (352, 2006, 1, 2, 2, 10),
 (353, 2006, 1, 2, 2, 20),
 (354, 2006, 1, 2, 2, 30),
 (355, 2006, 1, 2, 2, 40),
 (356, 2006, 1, 2, 2, 50),
 (357, 2006, 1, 2, 3, 0),
 (358, 2006, 1, 2, 3, 0),
 (359, 2006, 1, 2, 3, 10),
 (360, 2006, 1, 2, 3, 20),
 (361, 2006, 1, 2, 3, 30),
 (362, 2006, 1, 2, 3, 40),
 (363, 2006, 1, 2, 3, 50),
 (364, 2006, 1, 2, 4, 0),
 (365, 2006, 1, 2, 4, 0),
 (366, 2006, 1, 2, 4, 10),
 (367, 2006, 1, 2, 4, 20),
 (368, 2006, 1, 2, 4, 30),
 (369, 2006, 1, 2, 4, 40),
 (370, 2006, 1, 2, 4, 50),
 (371, 2006, 1, 2, 5, 0),
 (372, 2006, 1, 2, 5, 0),
 (373, 2006, 1, 2, 5, 10),
 (374, 2006, 1, 2, 5, 20),
 (375, 2006, 1, 2, 5, 30),
 (376, 2006, 1, 2, 5, 40),
 (377, 2006, 1, 2, 5, 50),
 (378, 2006, 1, 2, 6, 0),
 (379, 2006, 1, 2, 6, 0),
 (380, 2006, 1, 2, 6, 10),
 (381, 2006, 1, 2, 6, 20),
 (382, 2006, 1, 2, 6, 30),
 (383, 2006, 1, 2, 6, 40),
 (384, 2006, 1, 2, 6, 50),
 (385, 2006, 1, 2, 7, 0),
 (386, 2006, 1, 2, 7, 0),
 (387, 2006, 1, 2, 7, 10),
 (388, 2006, 1, 2, 7, 20),
 (389, 2006, 1, 2, 7, 30),
 (390, 2006, 1, 2, 7, 40),
 (391, 2006, 1, 2, 7, 50),
 (392, 2006, 1, 2, 8, 0),
 (393, 2006, 1, 2, 8, 0),
 (394, 2006, 1, 2, 8, 10),
 (395, 2006, 1, 2, 8, 20),
 (396, 2006, 1, 2, 8, 30),
 (397, 2006, 1, 2, 8, 40),
 (398, 2006, 1, 2, 8, 50),
 (399, 2006, 1, 2, 9, 0),
 (400, 2006, 1, 2, 9, 0),
 (401, 2006, 1, 2, 9, 10),
 (402, 2006, 1, 2, 9, 20),
 (403, 2006, 1, 2, 9, 30),
 (404, 2006, 1, 2, 9, 40),
 (405, 2006, 1, 2, 9, 50),
 (406, 2006, 1, 2, 10, 0),
 (407, 2006, 1, 2, 10, 0),
 (408, 2006, 1, 2, 10, 10),
 (409, 2006, 1, 2, 10, 20),
 (410, 2006, 1, 2, 10, 30),
 (411, 2006, 1, 2, 10, 40),
 (412, 2006, 1, 2, 10, 50),
 (413, 2006, 1, 2, 11, 0),
 (414, 2006, 1, 2, 11, 0),
 (415, 2006, 1, 2, 11, 10),
 (416, 2006, 1, 2, 11, 20),
 (417, 2006, 1, 2, 11, 30),
 (418, 2006, 1, 2, 11, 40),
 (419, 2006, 1, 2, 11, 50),
 (420, 2006, 1, 2, 12, 0),
 (421, 2006, 1, 2, 12, 0),
 (422, 2006, 1, 2, 12, 10),
 (423, 2006, 1, 2, 12, 20),
 (424, 2006, 1, 2, 12, 30),
 (425, 2006, 1, 2, 12, 40),
 (426, 2006, 1, 2, 12, 50),
 (427, 2006, 1, 2, 13, 0),
 (428, 2006, 1, 2, 13, 0),
 (429, 2006, 1, 2, 13, 10),
 (430, 2006, 1, 2, 13, 20),
 (431, 2006, 1, 2, 13, 30),
 (432, 2006, 1, 2, 13, 40),
 (433, 2006, 1, 2, 13, 50),
 (434, 2006, 1, 2, 14, 0),
 (435, 2006, 1, 2, 14, 0),
 (436, 2006, 1, 2, 14, 10),
 (437, 2006, 1, 2, 14, 20),
 (438, 2006, 1, 2, 14, 30),
 (439, 2006, 1, 2, 14, 40),
 (440, 2006, 1, 2, 14, 50),
 (441, 2006, 1, 2, 15, 0),
 (442, 2006, 1, 2, 15, 0),
 (443, 2006, 1, 2, 15, 10),
 (444, 2006, 1, 2, 15, 20),
 (445, 2006, 1, 2, 15, 30),
 (446, 2006, 1, 2, 15, 40),
 (447, 2006, 1, 2, 15, 50),
 (448, 2006, 1, 2, 16, 0),
 (449, 2006, 1, 2, 16, 0),
 (450, 2006, 1, 2, 16, 10),
 (451, 2006, 1, 2, 16, 20),
 (452, 2006, 1, 2, 16, 30),
 (453, 2006, 1, 2, 16, 40),
 (454, 2006, 1, 2, 16, 50),
 (455, 2006, 1, 2, 17, 0),
 (456, 2006, 1, 2, 17, 0),
 (457, 2006, 1, 2, 17, 10),
 (458, 2006, 1, 2, 17, 20),
 (459, 2006, 1, 2, 17, 30),
 (460, 2006, 1, 2, 17, 40),
 (461, 2006, 1, 2, 17, 50),
 (462, 2006, 1, 2, 18, 0),
 (463, 2006, 1, 2, 18, 0),
 (464, 2006, 1, 2, 18, 10),
 (465, 2006, 1, 2, 18, 20),
 (466, 2006, 1, 2, 18, 30),
 (467, 2006, 1, 2, 18, 40),
 (468, 2006, 1, 2, 18, 50),
 (469, 2006, 1, 2, 19, 0),
 (470, 2006, 1, 2, 19, 0),
 (471, 2006, 1, 2, 19, 10),
 (472, 2006, 1, 2, 19, 20),
 (473, 2006, 1, 2, 19, 30),
 (474, 2006, 1, 2, 19, 40),
 (475, 2006, 1, 2, 19, 50),
 (476, 2006, 1, 2, 20, 0),
 (477, 2006, 1, 2, 20, 0),
 (478, 2006, 1, 2, 20, 10),
 (479, 2006, 1, 2, 20, 20),
 (480, 2006, 1, 2, 20, 30),
 (481, 2006, 1, 2, 20, 40),
 (482, 2006, 1, 2, 20, 50),
 (483, 2006, 1, 2, 21, 0),
 (484, 2006, 1, 2, 21, 0),
 (485, 2006, 1, 2, 21, 10),
 (486, 2006, 1, 2, 21, 20),
 (487, 2006, 1, 2, 21, 30),
 (488, 2006, 1, 2, 21, 40),
 (489, 2006, 1, 2, 21, 50),
 (490, 2006, 1, 2, 22, 0),
 (491, 2006, 1, 2, 22, 0),
 (492, 2006, 1, 2, 22, 10),
 (493, 2006, 1, 2, 22, 20),
 (494, 2006, 1, 2, 22, 30),
 (495, 2006, 1, 2, 22, 40),
 (496, 2006, 1, 2, 22, 50),
 (497, 2006, 1, 2, 23, 0),
 (498, 2006, 1, 2, 23, 0),
 (499, 2006, 1, 2, 23, 10),
 (500, 2006, 1, 2, 23, 20),
 (501, 2006, 1, 2, 23, 30),
 (502, 2006, 1, 2, 23, 40),
 (503, 2006, 1, 2, 23, 50),
 (504, 2006, 1, 2, 24, 0),
 (505, 2006, 1, 2, 24, 0),
 (506, 2006, 1, 3, 0, 10),
 (507, 2006, 1, 3, 0, 20),
 (508, 2006, 1, 3, 0, 30),
 (509, 2006, 1, 3, 0, 40),
 (510, 2006, 1, 3, 0, 50),
 (511, 2006, 1, 3, 1, 0),
 (512, 2006, 1, 3, 1, 0),
 (513, 2006, 1, 3, 1, 10),
 (514, 2006, 1, 3, 1, 20),
 (515, 2006, 1, 3, 1, 30),
 (516, 2006, 1, 3, 1, 40),
 (517, 2006, 1, 3, 1, 50),
 (518, 2006, 1, 3, 2, 0),
 (519, 2006, 1, 3, 2, 0),
 (520, 2006, 1, 3, 2, 10),
 (521, 2006, 1, 3, 2, 20),
 (522, 2006, 1, 3, 2, 30),
 (523, 2006, 1, 3, 2, 40),
 (524, 2006, 1, 3, 2, 50),
 (525, 2006, 1, 3, 3, 0),
 (526, 2006, 1, 3, 3, 0),
 (527, 2006, 1, 3, 3, 10),
 (528, 2006, 1, 3, 3, 20),
 (529, 2006, 1, 3, 3, 30),
 (530, 2006, 1, 3, 3, 40),
 (531, 2006, 1, 3, 3, 50),
 (532, 2006, 1, 3, 4, 0),
 (533, 2006, 1, 3, 4, 0),
 (534, 2006, 1, 3, 4, 10),
 (535, 2006, 1, 3, 4, 20),
 (536, 2006, 1, 3, 4, 30),
 (537, 2006, 1, 3, 4, 40),
 (538, 2006, 1, 3, 4, 50),
 (539, 2006, 1, 3, 5, 0),
 (540, 2006, 1, 3, 5, 0),
 (541, 2006, 1, 3, 5, 10),
 (542, 2006, 1, 3, 5, 20),
 (543, 2006, 1, 3, 5, 30),
 (544, 2006, 1, 3, 5, 40),
 (545, 2006, 1, 3, 5, 50),
 (546, 2006, 1, 3, 6, 0),
 (547, 2006, 1, 3, 6, 0),
 (548, 2006, 1, 3, 6, 10),
 (549, 2006, 1, 3, 6, 20),
 (550, 2006, 1, 3, 6, 30),
 (551, 2006, 1, 3, 6, 40),
 (552, 2006, 1, 3, 6, 50),
 (553, 2006, 1, 3, 7, 0),
 (554, 2006, 1, 3, 7, 0),
 (555, 2006, 1, 3, 7, 10),
 (556, 2006, 1, 3, 7, 20),
 (557, 2006, 1, 3, 7, 30),
 (558, 2006, 1, 3, 7, 40),
 (559, 2006, 1, 3, 7, 50),
 (560, 2006, 1, 3, 8, 0),
 (561, 2006, 1, 3, 8, 0),
 (562, 2006, 1, 3, 8, 10),
 (563, 2006, 1, 3, 8, 20),
 (564, 2006, 1, 3, 8, 30),
 (565, 2006, 1, 3, 8, 40),
 (566, 2006, 1, 3, 8, 50),
 (567, 2006, 1, 3, 9, 0),
 (568, 2006, 1, 3, 9, 0),
 (569, 2006, 1, 3, 9, 10),
 (570, 2006, 1, 3, 9, 20),
 (571, 2006, 1, 3, 9, 30),
 (572, 2006, 1, 3, 9, 40),
 (573, 2006, 1, 3, 9, 50),
 (574, 2006, 1, 3, 10, 0),
 (575, 2006, 1, 3, 10, 0),
 (576, 2006, 1, 3, 10, 10),
 (577, 2006, 1, 3, 10, 20),
 (578, 2006, 1, 3, 10, 30),
 (579, 2006, 1, 3, 10, 40),
 (580, 2006, 1, 3, 10, 50),
 (581, 2006, 1, 3, 11, 0),
 (582, 2006, 1, 3, 11, 0),
 (583, 2006, 1, 3, 11, 10),
 (584, 2006, 1, 3, 11, 20),
 (585, 2006, 1, 3, 11, 30),
 (586, 2006, 1, 3, 11, 40),
 (587, 2006, 1, 3, 11, 50),
 (588, 2006, 1, 3, 12, 0),
 (589, 2006, 1, 3, 12, 0),
 (590, 2006, 1, 3, 12, 10),
 (591, 2006, 1, 3, 12, 20),
 (592, 2006, 1, 3, 12, 30),
 (593, 2006, 1, 3, 12, 40),
 (594, 2006, 1, 3, 12, 50),
 (595, 2006, 1, 3, 13, 0),
 (596, 2006, 1, 3, 13, 0),
 (597, 2006, 1, 3, 13, 10),
 (598, 2006, 1, 3, 13, 20),
 (599, 2006, 1, 3, 13, 30),
 (600, 2006, 1, 3, 13, 40),
 (601, 2006, 1, 3, 13, 50),
 (602, 2006, 1, 3, 14, 0),
 (603, 2006, 1, 3, 14, 0),
 (604, 2006, 1, 3, 14, 10),
 (605, 2006, 1, 3, 14, 20),
 (606, 2006, 1, 3, 14, 30),
 (607, 2006, 1, 3, 14, 40),
 (608, 2006, 1, 3, 14, 50),
 (609, 2006, 1, 3, 15, 0),
 (610, 2006, 1, 3, 15, 0),
 (611, 2006, 1, 3, 15, 10),
 (612, 2006, 1, 3, 15, 20),
 (613, 2006, 1, 3, 15, 30),
 (614, 2006, 1, 3, 15, 40),
 (615, 2006, 1, 3, 15, 50),
 (616, 2006, 1, 3, 16, 0),
 (617, 2006, 1, 3, 16, 0),
 (618, 2006, 1, 3, 16, 10),
 (619, 2006, 1, 3, 16, 20),
 (620, 2006, 1, 3, 16, 30),
 (621, 2006, 1, 3, 16, 40),
 (622, 2006, 1, 3, 16, 50),
 (623, 2006, 1, 3, 17, 0),
 (624, 2006, 1, 3, 17, 0),
 (625, 2006, 1, 3, 17, 10),
 (626, 2006, 1, 3, 17, 20),
 (627, 2006, 1, 3, 17, 30),
 (628, 2006, 1, 3, 17, 40),
 (629, 2006, 1, 3, 17, 50),
 (630, 2006, 1, 3, 18, 0),
 (631, 2006, 1, 3, 18, 0),
 (632, 2006, 1, 3, 18, 10),
 (633, 2006, 1, 3, 18, 20),
 (634, 2006, 1, 3, 18, 30),
 (635, 2006, 1, 3, 18, 40),
 (636, 2006, 1, 3, 18, 50),
 (637, 2006, 1, 3, 19, 0),
 (638, 2006, 1, 3, 19, 0),
 (639, 2006, 1, 3, 19, 10),
 (640, 2006, 1, 3, 19, 20),
 (641, 2006, 1, 3, 19, 30),
 (642, 2006, 1, 3, 19, 40),
 (643, 2006, 1, 3, 19, 50),
 (644, 2006, 1, 3, 20, 0),
 (645, 2006, 1, 3, 20, 0),
 (646, 2006, 1, 3, 20, 10),
 (647, 2006, 1, 3, 20, 20),
 (648, 2006, 1, 3, 20, 30),
 (649, 2006, 1, 3, 20, 40),
 (650, 2006, 1, 3, 20, 50),
 (651, 2006, 1, 3, 21, 0),
 (652, 2006, 1, 3, 21, 0),
 (653, 2006, 1, 3, 21, 10),
 (654, 2006, 1, 3, 21, 20),
 (655, 2006, 1, 3, 21, 30),
 (656, 2006, 1, 3, 21, 40),
 (657, 2006, 1, 3, 21, 50),
 (658, 2006, 1, 3, 22, 0),
 (659, 2006, 1, 3, 22, 0),
 (660, 2006, 1, 3, 22, 10),
 (661, 2006, 1, 3, 22, 20),
 (662, 2006, 1, 3, 22, 30),
 (663, 2006, 1, 3, 22, 40),
 (664, 2006, 1, 3, 22, 50),
 (665, 2006, 1, 3, 23, 0),
 (666, 2006, 1, 3, 23, 0),
 (667, 2006, 1, 3, 23, 10),
 (668, 2006, 1, 3, 23, 20),
 (669, 2006, 1, 3, 23, 30),
 (670, 2006, 1, 3, 23, 40),
 (671, 2006, 1, 3, 23, 50),
 (672, 2006, 1, 3, 24, 0),
 (673, 2006, 1, 3, 24, 0),
 (674, 2006, 1, 4, 0, 10),
 (675, 2006, 1, 4, 0, 20),
 (676, 2006, 1, 4, 0, 30),
 (677, 2006, 1, 4, 0, 40),
 (678, 2006, 1, 4, 0, 50),
 (679, 2006, 1, 4, 1, 0),
 (680, 2006, 1, 4, 1, 0),
 (681, 2006, 1, 4, 1, 10),
 (682, 2006, 1, 4, 1, 20),
 (683, 2006, 1, 4, 1, 30),
 (684, 2006, 1, 4, 1, 40),
 (685, 2006, 1, 4, 1, 50),
 (686, 2006, 1, 4, 2, 0),
 (687, 2006, 1, 4, 2, 0),
 (688, 2006, 1, 4, 2, 10),
 (689, 2006, 1, 4, 2, 20),
 (690, 2006, 1, 4, 2, 30),
 (691, 2006, 1, 4, 2, 40),
 (692, 2006, 1, 4, 2, 50),
 (693, 2006, 1, 4, 3, 0),
 (694, 2006, 1, 4, 3, 0),
 (695, 2006, 1, 4, 3, 10),
 (696, 2006, 1, 4, 3, 20),
 (697, 2006, 1, 4, 3, 30),
 (698, 2006, 1, 4, 3, 40),
 (699, 2006, 1, 4, 3, 50),
 (700, 2006, 1, 4, 4, 0),
 (701, 2006, 1, 4, 4, 0),
 (702, 2006, 1, 4, 4, 10),
 (703, 2006, 1, 4, 4, 20),
 (704, 2006, 1, 4, 4, 30),
 (705, 2006, 1, 4, 4, 40),
 (706, 2006, 1, 4, 4, 50),
 (707, 2006, 1, 4, 5, 0),
 (708, 2006, 1, 4, 5, 0),
 (709, 2006, 1, 4, 5, 10),
 (710, 2006, 1, 4, 5, 20),
 (711, 2006, 1, 4, 5, 30),
 (712, 2006, 1, 4, 5, 40),
 (713, 2006, 1, 4, 5, 50),
 (714, 2006, 1, 4, 6, 0),
 (715, 2006, 1, 4, 6, 0),
 (716, 2006, 1, 4, 6, 10),
 (717, 2006, 1, 4, 6, 20),
 (718, 2006, 1, 4, 6, 30),
 (719, 2006, 1, 4, 6, 40),
 (720, 2006, 1, 4, 6, 50),
 (721, 2006, 1, 4, 7, 0),
 (722, 2006, 1, 4, 7, 0),
 (723, 2006, 1, 4, 7, 10),
 (724, 2006, 1, 4, 7, 20),
 (725, 2006, 1, 4, 7, 30),
 (726, 2006, 1, 4, 7, 40),
 (727, 2006, 1, 4, 7, 50),
 (728, 2006, 1, 4, 8, 0),
 (729, 2006, 1, 4, 8, 0),
 (730, 2006, 1, 4, 8, 10),
 (731, 2006, 1, 4, 8, 20),
 (732, 2006, 1, 4, 8, 30),
 (733, 2006, 1, 4, 8, 40),
 (734, 2006, 1, 4, 8, 50),
 (735, 2006, 1, 4, 9, 0),
 (736, 2006, 1, 4, 9, 0),
 (737, 2006, 1, 4, 9, 10),
 (738, 2006, 1, 4, 9, 20),
 (739, 2006, 1, 4, 9, 30),
 (740, 2006, 1, 4, 9, 40),
 (741, 2006, 1, 4, 9, 50),
 (742, 2006, 1, 4, 10, 0),
 (743, 2006, 1, 4, 10, 0),
 (744, 2006, 1, 4, 10, 10),
 (745, 2006, 1, 4, 10, 20),
 (746, 2006, 1, 4, 10, 30),
 (747, 2006, 1, 4, 10, 40),
 (748, 2006, 1, 4, 10, 50),
 (749, 2006, 1, 4, 11, 0),
 (750, 2006, 1, 4, 11, 0),

In [38]:
str(data_timestamp.year).split('\n')

['169      2006',
 '170      2006',
 '171      2006',
 '172      2006',
 '173      2006',
 '         ... ',
 '61496    2006',
 '61497    2006',
 '61498    2006',
 '61499    2006',
 '61500    2006',
 'Name: year, Length: 61332, dtype: int64']

In [16]:
data_timestamp

           year  month  day  hour  minute
timeindex
170        2006      1    1     0      10
171        2006      1    1     0      20
172        2006      1    1     0      30
173        2006      1    1     0      40
174        2006      1    1     0      50
...         ...    ...  ...   ...     ...
61497      2006     12   31    23      40
61498      2006     12   31    23      50
61499      2006     12   31    24       0
61500      2006     12   31    24       0
61501      2006     12   31    24       0

[61332 rows x 5 columns]

Crear una columna con los timestamp consolidados de los datos del dataframe del tiempo.

In [ ]:
df_yeartm["Timestamp"] = df_yeartm.apply(lambda x : getTimestamp(x[1], x[2], x[3], x[4], x[5]), axis = 1)

In [ ]:
time_cols = []
for i in df3.index:
    time_cols.append(df_yeartm["Timestamp"][i])

In [ ]:
df3.index = time_cols

# 5. Dataframe con la informaciÃ³n extraÃ­da del archivo SQL

In [ ]:
df3.plot(subplots=True, figsize=(14,120));

In [ ]:
len(df3.columns)